spring:
  datasource:
    url: jdbc:h2:mem:notifications_db
    driver-class-name: org.h2.Driver
    username: admin
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  spring:
    application:
      name: notification-service

server:
  port: 8082