server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: game-events-service
          uri: http://localhost:8081
          predicates:
            - Path=/events/**
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notifications/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
